getSchedGo/getSchedGo/courses/urls.py
from django.conf.urls import url
from . import views
## name of app to call it's url without clash with other app's url. works as a namespaces
app_name = 'courses'
## list of all url's corresponding to type of get requests to access all the view 
urlpatterns = [
    url(r"^$", views.CourseView, name="CourseView"),
    url(r"^some/(?P<pk1>[a-zA-Z0-9_ ]+)/(?P<pk2>\w+)/$", views.CourseView, name="some"),
    url(r"^list/$",views.Enrollmentview, name="Enrollmentview"),
    url(r"^(?P<pk>[0-9]+)/add/$",views.UserAdder, name="UserAdder"),
    url(r"^(?P<pk>[0-9]+)/remove/$",views.UserDropper, name="UserDropper"),
    # url(r"^(?P<pk>[0-9]+)/anyDay/$", views.TodayStats, name="AnyDayStatistics"),
    # url(r"^list/$", views.EventBeforeDate, name="EventBeforeDate"),
    # url(r"^donelist/$", views.CompletedList, name="CompletedList"),
    # url(r"^(?P<pk>[0-9]+)/comp/$", views.MarkItCompleted, name="MarkItCompleted"),
    url(r"^EditCourse$", views.EditCourse, name="EditCourse"),
    url(r"^SelectCourse$", views.SelectCourse, name="SelectCourse"),
    url(r"^(?P<pk>[0-9]+)/ClaimCourse$", views.SelectCourse, name="ClaimCourse"),
    url(r"^(?P<pk>[0-9]+)/converttoevent$", views.AssignmentToEvent, name="AssignmentToEvent"),
    url(r"^(?P<pk>[0-9]+)/classtoevent$", views.ClassToEvent, name="ClassToEvent"),
    url(r"^(?P<pk>[0-9]+)/examtoevent$", views.ExamToEvent, name="ExamToEvent"),
    url(r"^(?P<pk>[0-9]+)/examppreptoevent$", views.ExamPrepToEvent, name="ExamPrepToEvent"),

]

getSchedGo/getSchedGo/getSchedGo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

from profiles import views as profiles_views
# from courses import views as course_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', profiles_views.home, name='home'),
    url(r'^about/$', profiles_views.about, name='about'),
    url(r'^profile/$', profiles_views.userProfile, name='profile'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^event/', include('Timetable.urls')),
    url(r'^stats/', include('statistics.urls')),
    url(r'^course/', include('courses.urls')),
    url(r'^suggestion/', include('Event_suggestion.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

getSchedGo/getSchedGo/courses/models.py
from django.db import models
from profiles.models import profile
# Create your models here.
## coursedetail model stores all the details of the course
# @details Student as well as Intructor profile are connected to coursedetail model
# All this course details help making basic timetable of student if the student is enrolled to the given course using the slot input done
# from csv file from asc official website
class coursedetail(models.Model):
	## Course Code
	code = models.CharField(max_length=7)
	## Course Name
	name = models.CharField(max_length=50)
	## Running Slot as per Institute TimeTable
	Slot = models.CharField(max_length=50,null=True,blank=True)
	## No. of Course Credits
	credit = models.IntegerField(null=True,blank=True)
	## Tuturial exist or not
	tutorial = models.BooleanField(default = False)
	## Tutorial Slot as per Institute TimeTable
	tutorialSlot = models.CharField(max_length=5,blank=True)
	## Instructor Profile. This Indirectly Connects course to events Created by Instructor for course
	instructor = models.ForeignKey(profile, on_delete=models.SET_NULL,null=True,blank = True)
	## Suggested Study Hours By Instructor
	PrescribedStudyHours = models.CharField(max_length=5,blank=True,null=True)
	## All student enrolled in the course
	Student = models.ManyToManyField(profile,related_name='Student_List',blank = True,)
	def __str__(self):
		return self.code

getSchedGo/getSchedGo/courses/forms.py
from django import forms
from .models import coursedetail

## This is a django form helping to ask course code from user
# @detail Getting an input from user it searches for course with given
# text as suffix or prefix case insensitive
class CourseForm(forms.Form):
	code = forms.CharField(max_length=7)

## This is a djangoModel form to update the data of courseDetail model
# @details excluding the code and slots related to it

class CourseEditForm(forms.ModelForm):
	class Meta:
		model = coursedetail
		exclude = ('code','Slot','instructor','Student','tutorial','tutorialSlot')

getSchedGo/getSchedGo/courses/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import coursedetail
from .forms import CourseForm , CourseEditForm
from profiles.models import profile
from Timetable.models import *
from Timetable.PeerSuggestion import getDuration
from Timetable.slots import SlotPattern as sp
from Timetable.slotconverter import slotInterval
from Timetable.schedule import fixedScheduleAdder
# Create your views here.

## This view is student Dashboard for various events published by instructor
# @param request basic call for a view in django
# @param getargument1 helps to show all the events of a simgle course
# @param getargument2 helps to show only a particular type of events
# @details allows user to view assignments classes exams published by instructors of various courses
# Here from this view he can easily choose the event and schedule it
#
# Scheduled events will flag out among rest of the events
def CourseView(request,pk1='nan',pk2='nan'):
    user=request.user
    ## List of courses in which student is ennrolled
    CourseList=coursedetail.objects.filter(Student = user.profile)
    ## Apply course filter. 'nan' means for all courses
    if(pk1=='nan'):
        Coursereq=coursedetail.objects.filter(Student = user.profile)
    else:
        Coursereq=coursedetail.objects.filter(code=pk1)
    template = 'courseview.html'
    AssignmentList=[]
    ClassList=[]
    ExamList=[]
    # fills in the course events in Lists
    for Course in Coursereq:
        AssignmentList.extend(InstructorAssignment.objects.filter(UserProfile=Course.instructor))
        ExamList.extend(InstructorExam.objects.filter(UserProfile=Course.instructor))
        ClassList.extend(InstructorClass.objects.filter(UserProfile=Course.instructor))
    ## Applies Task filter (class/assignment/Exam)
    if(pk2=='a'):
        ClassList=[]
        ExamList=[]
    elif(pk2=='c'):
        AssignmentList=[]
        ExamList=[]
    elif(pk2=='e'):
        ClassList=[]
        AssignmentList=[]
    else:
        print("ok")
    ## these loops check which course event is already added. maintain a list of value 0/1 depending
    # on scheduled or unscheduled by the current user
    supportAssign = []
    for assign in AssignmentList:
        i=Event.objects.filter(UserProfile = user.profile,CreatorType='1',CreatorId=assign.id).count()
        supportAssign.append(i)
    supportClass = []
    for Class in ClassList:
        i=Event.objects.filter(UserProfile = user.profile,CreatorType='2',CreatorId=Class.id).count()
        supportClass.append(i)
    supportExam = []
    supportExamPrep = []
    for Exam in ExamList:
        i=Event.objects.filter(UserProfile = user.profile,CreatorType='3',CreatorId=Exam.id).count()
        j=Event.objects.filter(UserProfile = user.profile,CreatorType='4',CreatorId=Exam.id).count()
        supportExam.append(i)
        supportExamPrep.append(j)
    ## zipping relevant lists with user's history of scheduling
    AssignmentList = zip(AssignmentList,supportAssign)
    ClassList = zip(ClassList,supportClass)
    ExamList = zip(ExamList,supportExam,supportExamPrep)
    context = {'user': user,'CourseList': CourseList, 'AssignmentList': AssignmentList, 'ClassList': ClassList, 'ExamList': ExamList,'pk1': pk1,'pk2': pk2}
    print(CourseList)
    print(AssignmentList)
    print(ClassList)
    print(ExamList)
    return render(request,template,context)
## View to enroll into a Course
# @param request  basic call for a view in django
# @param pk getargument which contains coursedetail model id
# @details This view enrolls a user into a course.
# It also adds the regular classes to user schedule automatically
# For instructor it acts a way to bind himself with a course
def UserAdder(request,pk):
    ToChange = get_object_or_404(coursedetail,pk=pk)
    user = request.user
    if user.profile.instructor:
        if ToChange.instructor is None:
            ToChange.instructor = user.profile
        else :
            pass
    else:
        ToChange.Student.add(user.profile)
        ToChange.save()
        ## to add the classes automatically to student schedule for the next 3 days
        for i in range(4):
            Day = date.today()+timedelta(days=i)
            WEEKDAY = Day.weekday() + 1
            slots = ToChange.Slot
            slots = slots.split(" ")
            slots.pop()
            for s in slots:
                d,st,et = slotInterval(sp[s])
                if d == str(WEEKDAY):
                    st=st.split(":")
                    et=et.split(":")
                    st = time(int(st[0]),int(st[1]),int(st[2]))
                    et = time(int(et[0]),int(et[1]),int(et[2]))
                    stu = Event(UserProfile = user.profile,name = ToChange.name+" Class",
                        StartTime = st, StartDate = Day, TimeSettings = 'B',
                        EndTime = et, EndDate = Day, Priority = '4', Type='A')
                    stu.save()
                    fixedScheduleAdder(stu,user)
    return redirect('courses:Enrollmentview')
## view for dropping the course
# @param request  basic call for a view in django
# @param pk course model id of course to be dropped
def UserDropper(request,pk):
    ToChange = get_object_or_404(coursedetail,pk=pk)
    user = request.user
    ## By the way this was just for prototype. Currently instuctor can't get rid of the course.
    # This link will be activated at the end of the semester
    if user.profile.instructor:
        if ToChange.instructor == user.profile:
            ToChange.instructor = None
        else :
            pass
    else:
        if user.profile in ToChange.Student.all():
            ToChange.Student.remove(user.profile)
        else:
            pass
    ToChange.save()
    return redirect('courses:Enrollmentview')
## view to search querry for available courses
# @param request  basic call for a view in django
# Does an intelligent searching of course by it's course code throughout the database
#
# Provides links to course enrollment as well as course dropping to the student
@login_required
def Enrollmentview(request):
    template = 'Enrollment.html'
    user = request.user
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['code']
            detail = coursedetail.objects.filter(code__istartswith=text) | coursedetail.objects.filter(code__iendswith=text)
            exList = []
            for courses in detail:
                en = coursedetail.objects.filter(Student = user.profile, code = courses.code)
                if not en:
                    exList.append('1')
                else:
                    exList.append('0')
            detail = list(zip(detail,exList))
        return render(request,template,{'form': form, 'courseDetail': detail, 'user': user})
    else:
        form = CourseForm()
        return render(request,template,{'form': form,})
## View for instructor to claim a course as his
# @param request  basic call for a view in django
# @param pk courseid
@login_required
def SelectCourse(request,pk=-1):
    template = 'selectcourse.html'
    text = " "
    user = request.user
    if request.method == 'POST':
        if(pk==-1):
            form=CourseForm(request.POST)
            if form.is_valid():
                text = form.cleaned_data['code']
                detail = coursedetail.objects.filter(code__istartswith=text) | coursedetail.objects.filter(code__iendswith=text)
                All = coursedetail.objects.filter(instructor = user.profile)
            return render(request,template,{'form': form, 'text': text, 'courseDetail': detail, 'user': user, 'Aux': All})

    else: #for get request i.e. when page opens on browser
        if(pk==-1):
            form = CourseForm() #Blank form where user will enter course
            return render(request,template,{'form': form, 'text': text, 'user': user})
        else:
            All = coursedetail.objects.filter(instructor = user.profile)
            print(pk)
            if not All:
                print("ys")
                courseToClaim = get_object_or_404(coursedetail, pk=pk)
                courseToClaim.instructor = user.profile
                courseToClaim.save()
                return redirect('home')
            else:
                print("no")
                return redirect('home')
## Convert an Assignment object of a course to event of user
# @param request  basic call for a view in django
# @param pk InstructorAssignment id
# Saves a sample of that event and redirects to the eventForm with its instance to edit few details and schedule it with highest priority
# Priority is kept indespensable with variable time setting
def AssignmentToEvent(request, pk):
    instance= get_object_or_404(InstructorAssignment, pk=pk)
    q = Event(UserProfile= request.user.profile,
    name= instance.name,
    CreatorType= '1',
    CreatorId= pk,
    Description=instance.Description,
    TimeSettings='C',
    StartTime = instance.StartTime,
    StartDate = instance.StartDate,
    Duration = instance.ExpectedDuration,
    DeadLineTime=instance.DeadLineTime,
    DeadLineDate=instance.DeadLineDate,
    Priority = '4',
    Type = 'B')
    q.save()
    return redirect('Timetable:EditEvent',pk=q.id)
## Convert an Class object of a course to event of user
# @param request  basic call for a view in django
# @param pk InstructorClass id
# Saves a sample of that event and redirects to the eventForm with its instance to edit few details and schedule it with highest priority
# Priority is kept indespensable with fixed time setting.
def ClassToEvent(request,pk):
    instance=get_object_or_404(InstructorClass, pk=pk)
    Start= datetime.combine(instance.Date, instance.StartTime)
    End= datetime.combine(instance.Date, instance.EndTime)
    q= Event(UserProfile=request.user.profile,
    CreatorType = '2',
    CreatorId = pk,

getSchedGo/getSchedGo/courses/templates/Enrollment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<style>
.glyphicon {
    font-size: 2	0px;
}
</style>
<div class="col-md-4 col-md-offset-2">

	 <form method="post">
	 	{% csrf_token %}
	 	{{ form|crispy }}
			<button class="btn btn-primary " type="submit">Submit</button>
		</form>
</div>


{% for courses,stat in courseDetail %}
<div class="col-md-6 col-md-offset-2">
	<div class='row event-holder'>

	<div class='col-md-8'>
<h3>
Code: {{ courses.code }}
</h3>
<h3>
Name: {{ courses.name }}
</h3><h3>
Slot Number: {{ courses.Slot }}
</h3><h3>
Credit: {{ courses.credit }}
</h3>
{% if courses.instructor %}
	<h3>Instructor: {{ courses.instructor.name }}</h3>
{% else %}
	<h3>Instructor: Not Alloted</h3>
{% endif %}
{% if courses.PrescribedStudyHours %}
	<h3>Prescribed Study Hours: {{ courses.PrescribedStudyHours }}</h3>
{% endif %}
</div>
<div class="col-md-2"></div>
<div class="col-md-4">
	{% if stat == '1' %}
	<a href="{% url 'courses:UserAdder' courses.id %}"><button type="button" class="btn btn-default btn-sm">
          <span class="glyphicon glyphicon-ok"></span>Enroll
        </button></a><br><br>
	{% else %}
	<a href="{% url 'courses:UserDropper' courses.id %}">  <button type="button" class="btn btn-danger btn-sm"; style="height: 60px; width: 100px;">
          <span class="glyphicon glyphicon-remove"></span> <font size="5" color="#ffcc00">Drop</font>
        </button></a> <br>
	{% endif %}
</div>
</div>
</div>

{% endfor %}
{% endblock %}

getSchedGo/getSchedGo/courses/templates/courseedit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-md-6 col-md-offset-3">
{% if form %}
<form method="POST">
	{% csrf_token %}
{{ form|crispy }}
  <button type="submit" class="btn btn-primary">SUBMIT</button>
</form>
{% else %}
PLease enroll for a course
{% endif %}
</div>
{% endblock %}

getSchedGo/getSchedGo/courses/templates/courseview.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block styles %}
<style type="text/css">
  .affix {
    top:50px;
    position: fixed;
    width: 100%;
    margin-left: 0;
    z-index: 1 !important;
  }
  .navbar {
      margin-bottom: 0px;
  }
</style>
{% endblock %}
{% block bars %}
<div align="center">Hi {{ user }}</div>
<nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="40">
 <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mynavbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

<div id="mynavbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="dropdown" align="right">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Course <span class="caret"></span></a>
              <ul class="dropdown-menu">
								<li><a href="{% url 'courses:some' 'nan' pk2 %}">All</a></li>
<!-- using if for different view if user is logged in or not -->
							{% for courses in CourseList %}
                <li><a href="{% url 'courses:some' courses.code pk2 %}">{{ courses.code }}</a></li>
							{% endfor %}
<!--                 <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li> -->
              </ul>
							<li class="dropdown" align="right">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Event Type <span class="caret"></span></a>
		              <ul class="dropdown-menu">
										<li><a href="{% url 'courses:some' pk1 'nan' %}">All</a></li>
										<li><a href="{% url 'courses:some' pk1 'a' %}">Assignment</a></li>
										<li><a href="{% url 'courses:some' pk1 'c' %}">Classes</a></li>
										<li><a href="{% url 'courses:some' pk1 'e' %}">Exam</a></li>
		<!-- using if for different view if user is logged in or not -->
		<!--                 <li role="separator" class="divider"></li>
		                <li class="dropdown-header">Nav header</li>
		                <li><a href="#">Separated link</a></li>
		                <li><a href="#">One more separated link</a></li> -->
		              </ul>
            </li>
        </ul>
      </div>

  </div>
</nav>
{% endblock %}
{% block content %}
{% if AssignmentList %}
<p>
 {% for Assignment,added in AssignmentList %}
 <!-- {% if Event.ScheduledStartTime %}
 <div class="row event-holder" id="event{{ forloop.counter }}" style="background-color: white; color:#033a22; font-family: 'Alegreya SC';font-size: 24px;">
 {% else %}
 <div class="row event-holder" id="event{{ forloop.counter }}" style="font-family: 'Alegreya SC';font-size: 24px;">
 {% endif %}     -->
 <div class="row event-holder" id="event{{ forloop.counter }}" style="font-family: 'Alegreya SC';font-size: 24px;">
 <div class="col-md-8">
			 <h3> {{ Assignment.name }} </h3>
			 <!-- <h4> From : {{Event.StartDate }} {{ Event.StartTime }} </h4>
			 <h4> To : {{ Event.EndDate  }} {{ Event.EndTime }} </h4> -->
			 <h4> DeadLine : {{ Assignment.DeadLineDate }} {{ Assignment.DeadLineTime }} </h4>
		</div>
		<div class="col-md-4" >
      {% if added == 0 %}
		<a href="{% url 'courses:AssignmentToEvent' Assignment.id %}"><span class="glyphicon glyphicon-edit shaker"></span></a>
      {% else %}
      <b><font size="6" color="#4d79ff">Already added, don't worry!!</font></b>
      {% endif %}
			 </div>
	</div>
 {% endfor %}
</p>
{% endif %}


{% if ExamList %}
<p>
 {% for Exam,added,prep in ExamList %}
 <!-- {% if Event.ScheduledStartTime %}
 <div class="row event-holder" id="event{{ forloop.counter }}" style="background-color: white; color:#033a22; font-family: 'Alegreya SC';font-size: 24px;">
 {% else %}
 <div class="row event-holder" id="event{{ forloop.counter }}" style="font-family: 'Alegreya SC';font-size: 24px;">
 {% endif %}     -->
 <div class="row event-holder" id="event{{ forloop.counter }}" style="font-family: 'Alegreya SC';font-size: 24px;">
 <div class="col-md-8">
	 <h3> {{ Exam.name }} </h3>
	 <h4> On : {{Exam.Date }} </h4>
	 <h4> From {{ Exam.StartTime }} To {{ Exam.EndTime }} </h4>
	 <h4> At : {{ Exam.Venue }} </h4>
	 <h4> Preparation : {{ Exam.PreparationDuration }}
		</div>
		<div class="col-md-4" >
    {% if added == 0 %}
		<a href="{% url 'courses:ExamToEvent' Exam.id %}"><span class="glyphicon glyphicon-edit shaker"></span></a>
    {% else %}
    added
    {% endif %}
    {% if prep == 0 %}
		<a href="{% url 'courses:ExamPrepToEvent' Exam.id %}" class="shaker"><span class="glyphicon glyphicon-calendar"></span></a>
    {% else %}
    added
    {% endif %}
    </div>
	</div>
 {% endfor %}
</p>
{% endif %}

{% if ClassList %}

 {% for Class,added in ClassList %}
 <!-- {% if Event.ScheduledStartTime %}
 <div class="row event-holder" id="event{{ forloop.counter }}" style="background-color: white; color:#033a22; font-family: 'Alegreya SC';font-size: 24px;">
 {% else %}
 <div class="row event-holder" id="event{{ forloop.counter }}" style="font-family: 'Alegreya SC';font-size: 24px;">
 {% endif %}     -->
 <div class="row event-holder" id="event{{ forloop.counter }}" style="font-family: 'Alegreya SC';font-size: 24px;">
 <div class="col-md-8">
	 <h3> {{ Class.name }} </h3>
	 <h4> From : {{Class.StartDate }} {{ Class.StartTime }} </h4>
	 <h4> To : {{ Class.EndDate }} {{ Class.EndTime }} </h4>
	 <h4> At : {{ Class.Venue }} </h4>
    </div>
    <div class="col-md-4" >
    {% if added == 0 %}
    {% if Class.Compulsory %}
    <h5>This Class Is Compulsary</h5>
    {% endif %}
		<a href="{% url 'courses:ClassToEvent' Class.id %}"><span class="glyphicon glyphicon-edit shaker"></span></a>
    {% else %}
    added
    {% endif %}
		</div>
	</div>
 {% endfor %}
</p>
{% endif %}
</div>
{% endblock %}

getSchedGo/getSchedGo/courses/templates/selectcourse.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-md-4 col-md-offset-2">

	 <form method="post">
	 	{% csrf_token %}
	 	{{ form|crispy }}
			<button type="submit">Submit</button>
		</form>
</div>
<div class="col-md-8 col-md-offset-2">
{% for course in courseDetail %}
<div class='event-holder'>
<h3>
Code: {{ course.code }}
</h3><br>
<h3>
Name: {{ course.name }}
</h3><br><h3>
Slot Number: {{ course.Slot }}
</h3><br><h3>
Credit: {{ course.credit }}
</h3><br>
{% if course.tutorial %}
<h3>
Tutorial Slot: {{ course.tutorialSlot }}
</h3><br>
{% endif %}
{% if request.user.profile.instructor %}
<h3>
	{% if not course.instructor %}
	{% if not Aux %}
	<!-- <a href="{% url 'courses:ClaimCourse' course.id %}">I am the Instructor</a> -->
	<a href="{% url 'courses:ClaimCourse' course.id %}" class="btn btn-danger"><h4>I am the Instructor</h4></button></a>
	{% endif %}
	{% endif %}
</h3><br>
{% endif %}
</div>
{% endfor %}
</div>
{% endblock %}