getSchedGo/getSchedGo/Timetable/urls.py
from django.conf.urls import url
from . import views
app_name = 'Timetable'
urlpatterns = [
    url(r"^$", views.EventList, name="EventList"),
    url(r"^create/$", views.CreateEvent, name="CreateEvent"),
    url(r"^(?P<pk>[0-9]+)/edit$", views.CreateEvent, name="EditEvent"),
    url(r"^(?P<pk>[0-9]+)/delete$", views.DeleteEvent, name="DeleteEvent"),
    url(r"^(?P<pk>[0-9]+)/desched$", views.DescheduleEvent, name="DescheduleEvent"),
    url(r"^(?P<pk>[0-9]+)/sort$", views.EventList, name="SortEvent"),
    url(r"^CreateAssignment$", views.CreateAssignment, name="CreateAssignment"),
    url(r"^Assignments$", views.Assignments, name="AssignmentList"),
    url(r"^(?P<pk>[0-9]+)/SortAssignment$", views.Assignments, name="SortAssignment"),
    url(r"^CreateClass$", views.CreateClass, name="CreateClass"),
    url(r"^Classes$", views.Classes, name="ClassList"),
    url(r"^(?P<pk>[0-9]+)/SortClass$", views.Classes, name="SortClass"),
    url(r"^CreateExam$", views.CreateExam, name="CreateExam"),
    url(r"^Exams$", views.Exams, name="ExamList"),
    url(r"^(?P<pk>[0-9]+)/SortExam$", views.Exams, name="SortExam"),
    url(r'^today/$',views.Schedules, name = "Schedule"),
   
]

getSchedGo/getSchedGo/courses/urls.py
from django.conf.urls import url
from . import views
## name of app to call it's url without clash with other app's url. works as a namespaces
app_name = 'courses'
## list of all url's corresponding to type of get requests to access all the view 
urlpatterns = [
    url(r"^$", views.CourseView, name="CourseView"),
    url(r"^some/(?P<pk1>[a-zA-Z0-9_ ]+)/(?P<pk2>\w+)/$", views.CourseView, name="some"),
    url(r"^list/$",views.Enrollmentview, name="Enrollmentview"),
    url(r"^(?P<pk>[0-9]+)/add/$",views.UserAdder, name="UserAdder"),
    url(r"^(?P<pk>[0-9]+)/remove/$",views.UserDropper, name="UserDropper"),
    # url(r"^(?P<pk>[0-9]+)/anyDay/$", views.TodayStats, name="AnyDayStatistics"),
    # url(r"^list/$", views.EventBeforeDate, name="EventBeforeDate"),
    # url(r"^donelist/$", views.CompletedList, name="CompletedList"),
    # url(r"^(?P<pk>[0-9]+)/comp/$", views.MarkItCompleted, name="MarkItCompleted"),
    url(r"^EditCourse$", views.EditCourse, name="EditCourse"),
    url(r"^SelectCourse$", views.SelectCourse, name="SelectCourse"),
    url(r"^(?P<pk>[0-9]+)/ClaimCourse$", views.SelectCourse, name="ClaimCourse"),
    url(r"^(?P<pk>[0-9]+)/converttoevent$", views.AssignmentToEvent, name="AssignmentToEvent"),
    url(r"^(?P<pk>[0-9]+)/classtoevent$", views.ClassToEvent, name="ClassToEvent"),
    url(r"^(?P<pk>[0-9]+)/examtoevent$", views.ExamToEvent, name="ExamToEvent"),
    url(r"^(?P<pk>[0-9]+)/examppreptoevent$", views.ExamPrepToEvent, name="ExamPrepToEvent"),

]

getSchedGo/getSchedGo/getSchedGo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

from profiles import views as profiles_views
# from courses import views as course_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', profiles_views.home, name='home'),
    url(r'^about/$', profiles_views.about, name='about'),
    url(r'^profile/$', profiles_views.userProfile, name='profile'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^event/', include('Timetable.urls')),
    url(r'^stats/', include('statistics.urls')),
    url(r'^course/', include('courses.urls')),
    url(r'^suggestion/', include('Event_suggestion.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

getSchedGo/getSchedGo/statistics/urls.py
from django.conf.urls import url
from . import views
## app_name helps django index urls mentioned below and for calling
# these urls is app_name:urlName. this helps developers forget the name they might have given
# to an app in different app 
app_name = 'statistics'
## These are list urlPatterns for this app. Ones containing 
# pk are the ones carrying parameters to corresponding view to do something specific
# for different call of same view with different parameters
urlpatterns = [
    url(r"^$", views.TodayStats, name="TodayStatistic"),
    url(r"^(?P<pk>[0-9]+)/anyDay/$", views.TodayStats, name="AnyDayStatistics"),
    url(r"^list/$", views.EventBeforeDate, name="EventBeforeDate"),
    url(r"^donelist/$", views.CompletedList, name="CompletedList"),
    url(r"^(?P<pk>[0-9]+)/comp/$", views.MarkItCompleted, name="MarkItCompleted"),
    url(r"^csvlist/$", views.AheadOfTime, name="AheadOfTime"),
    url(r"^google/$",views.googleConnector, name="googleConnector")
    
]

getSchedGo/getSchedGo/Timetable/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from .models import *
from datetime import *
from .schedule import fixedScheduleAdder, NewVariableEvent1
from profiles.models import createSched
from .EventPicker import eventList
from django.contrib import messages
from .PeerSuggestion import getDuration
from django.db.models import Q

## A model for creating an Eventor Editing a previous one
# @param Request,EventId
# @details First it looks after the pk parameter, if it is blank it creates a blank form.
# If pk contains a value it gets the object with that id from the database and makes a prefilled
# form out of it.
# User has to fill in the details or edit and then submit. The form saves the event to the database amd calls
# the scheduler.py. Depending on its return value it will show a message whether the event was
# scheduled or it has a slot clash etc.
@login_required
def CreateEvent(request,pk=-1):
    user = request.user
    ## When Submit is pressed
    if request.method == 'POST':
        # If new event
        if(pk==-1):
            form = EventForm(request.POST)
        # If event exists. This block deschedules it first to free up the slots
        else:
            prev=get_object_or_404(Event, pk=pk)
            form = EventForm(request.POST, instance = prev)
            SlotToFree = Slots.objects.filter(EventConnected = prev)
            for slot in SlotToFree:
                slot.EventConnected = None
                slot.save()
            prev.ScheduledStartTime=None
            prev.ScheduledEndTime=None
        if form.is_valid():
            Eve = form.save(commit=False)
            Eve.UserProfile = user.profile
            Eve.save()
            ## Code here onwards handles issues regarding Scheduling
            if Eve.TimeSettings=='B':
                a=fixedScheduleAdder(Eve,user)
                if a == 2:
                    messages ="Sorry, you are thinking of too far away. Have a life a come back later.We have saved your event. You can go to home. Still if you made a mistake while entering, Goto EventList"
                    formToRestructure = EventForm(instance=Eve)
                    return render(request,'CreateEvent.html',{'user': user, 'form': formToRestructure, 'message': messages})
                elif a == 1:
                    messages ="We have saved your event.This timing is already scheduled. You can change the timing or try making event of variable type by going to EventList"
                    formToRestructure = EventForm(instance=Eve)
                    return render(request,'CreateEvent.html',{'user': user, 'form': formToRestructure, 'message': messages})
                elif a == 3:
                    messages ="This event clashed with some event that was less useful for you. Please checkout the newly scheduled time-table. Your earlier event if not scheduled automatically will be available in event list"
                    formToRestructure = EventForm(instance=Eve)
                    return render(request,'CreateEvent.html',{'user': user, 'form': formToRestructure, 'message': messages})
            elif Eve.TimeSettings=='C':
                a=NewVariableEvent1(Eve,user)
                print(a)
            return redirect('Timetable:EventList')
    # When Edit or create button is pressed
    else:
        template = 'CreateEvent.html'
        # for new events
        if(pk==-1):
            form = EventForm()
            context = {'user': user, 'form': form}
        # for existing events and event created using Course events and Suggestion API
        else:
            prev=get_object_or_404(Event, pk=pk)
            form = EventForm(instance=prev)
            context = {'user': user, 'form': form}
            # collects Peer Duration data for assignments and exam prearation events
            if prev.CreatorType =='4' or prev.CreatorType=='1':
                dataList = []
                dataList,freqList,mean = getDuration(prev.CreatorType,prev.CreatorId)
                maximum = max(freqList, key=freqList.get)
                multiplier=100//freqList[maximum]
                # print(freqList.items())
                context = {'user': user, 'form': form, 'freqList': freqList.items(),'mult': multiplier}
                template = 'CreateEventSpecial.html'
        return render(request,template,context)


## A method for displaying EventList
# @param request,pk i.e id
# @details Depending on the pk parameter it will display various kind of events of the user.
# If pk is null(default is -1) or 0 it will display all the events .
# If pk is 2 it will display only the scheduled events.
# If pk is 3 it will display only the unscheduled events.
# For any other value of pk it will sort the events according to StartDate and StartTime
# and display accordingly. Actually it passes the list of filtered/unfiltered events as a
# context to the template 'EventList.html'
@login_required
def EventList(request,pk=-1):
    user = request.user
    # Various Filters
    if(pk==-1 or pk=='0'):
        List = Event.objects.filter(UserProfile=user.profile).exclude(Type='A', CreatorType ='0')
    elif(pk == '2'):
        List = Event.objects.filter(UserProfile=user.profile).exclude(ScheduledStartTime=None).exclude(Type='A', CreatorType ='0')
        print(List)
    elif(pk == '3'):
        List = Event.objects.filter(UserProfile=user.profile,ScheduledStartTime__isnull=True).exclude(Type='A', CreatorType ='0')
    elif(pk == '4'):
        List = Event.objects.filter(UserProfile=user.profile,Completed = False).exclude(Type='A', CreatorType ='0')
    else:
        print(pk)#now if more wanted then add pk=='3' so on
        List = Event.objects.filter(UserProfile=user.profile).order_by('StartDate','StartTime').exclude(Type='A', CreatorType ='0')
    # print(List)
    context = {'user': user,'List': List}
    template = 'EventList.html'
    # print(List)
    return render(request,template,context)


## A method displaying all events of a week, from three days before to four days after
# @param request
# @details It makes a list of lists. The first element of each of the list is a dailysched object and the second
# element is a list of events corresponding to the active day of the dailysched object.It passes the list
# as a context to 'todayschedule.html'
# createsched checks if there is a dailysched object with active day equal to today, if there isn't it creates one.
# EventList creates a eventlist corresponding to the day.

## For displaying Schedule in timetable
@login_required
def Schedules(request):
    user=request.user
    SchedList = []
    # Gets DayScheds (Day containers) and Creates them if they doesn't exist
    for i in range(-3,4):
        createSched(date.today() + timedelta(days=i),user.profile,user)
        Day = get_object_or_404(DailySched, UserProfile = user.profile, Active_day = (date.today() + timedelta(days=i)))
        EventList = eventList(Day)
        print(EventList)
        SchedList.append([Day, EventList])
    # SchedToday = DailySched.objects.filter(UserProfile = user.profile, Active_day = date.today())
    print(SchedList)
    context = {'user': user, 'range': range(0,24),'SchedList': SchedList}
    template = 'todayschedule.html'
    return render(request,template,context)


## A method for deleting events
# @param request, pk i.e. id
# @details Gets the Event by its id and frees the corresponding slot connected by setting the slot's
# Eventconnected field to none and also deletes the event from database.

@login_required
def DeleteEvent(request,pk):
    ToBeRemoved = get_object_or_404(Event,pk=pk)
    SlotToFree = Slots.objects.filter(EventConnected = ToBeRemoved)
    for slot in SlotToFree:
        slot.EventConnected = None
        slot.save()
    ToBeRemoved.delete()
    return redirect('Timetable:EventList')


## A method for descheduling events.
# @param request, pk i.e. id
# @details First it gets the event by its id from the databases and frees the corresponding slot connected
# by setting the slot's Eventconnected field to none. Then it sets the event's ScheduledStartTime and
# ScheduledEndTime to None.
@login_required
def DescheduleEvent(request,pk):
    ToBeDescheduled = get_object_or_404(Event,pk=pk)
    SlotToFree = Slots.objects.filter(EventConnected = ToBeDescheduled)
    print(SlotToFree)
    for slot in SlotToFree:
        slot.EventConnected = None
        slot.save()
    ToBeDescheduled.ScheduledStartTime=None
    ToBeDescheduled.ScheduledEndTime=None
    ToBeDescheduled.save()
    return redirect('Timetable:EventList')

## A view for creating an assignment
# @param request
# @details First it checks if the user is an instructor or not.If it is,if the request is Post , it creates an InstructorAssignmentForm. If the form is valid,
# it creates a assignment object out of it ans saves it in the database.If there is a get request,
# it creates a blank form and passes it as a context to the template 'CreateEvent.html'. If the user is
# not an instructor it just redirects to the home.
@login_required
def CreateAssignment(request):
    user = request.user
    if (request.user.profile.instructor):
        if (request.method=='POST'):
            form = InstructorAssignmentForm(request.POST)
            if form.is_valid():
                Assign = form.save(commit=False)
                Assign.UserProfile = user.profile
                Assign.save()
            return redirect('home')
        else:
            form = InstructorAssignmentForm()
            context={'user': user, 'form': form}
            template = 'CreateEvent.html'
            return render(request,template,context)
    else:
        return redirect('home')


## A view for creating a Class
# @param request
# @details First it checks if the user is an instructor or not.If it is,if the request is Post , it creates an InstructorClassForm. If the form is valid,

getSchedGo/getSchedGo/Timetable/templates/Assignment.html
{% extends 'base.html'%}
{% block otherinclusions %}
<link href='https://fonts.googleapis.com/css?family=Alegreya SC' rel='stylesheet'>
{% endblock %}
{% block styles %}
<style type="text/css">
  .affix {
    top:50px;
    position: fixed;
    width: 100%;
    margin-left: 0;
    z-index: 1 !important;
  }
  .navbar {
      margin-bottom: 0px;
  }
</style>
{% endblock %}
{% block bars %}
<div align="center">Hi {{ user }}</div>
<nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="40">
 <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mynavbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div id="mynavbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          <li><a href="{% url 'Timetable:SortAssignment' 0 %}">Sort by ID</a></li>
          <li><a href="{% url 'Timetable:SortAssignment' 1 %}">Sort by DATE</a></li>
        </ul>
      </div>

  </div>
</nav>
{% endblock %}

{% block content %}<!-- Using extend everything to be displayed are kept in extend.
It is just as if part of content in block of actually in base.html -->




  {% if List %}
<p>
   {% for Assignment in List %}
   <div class="row event-holder" id="event{{ forloop.counter }}" style="font-family: 'Alegreya SC';font-size: 24px;">
   <div class="col-md-8">
         <h3> {{ Assignment.name }} </h3>
         <h4> From : {{Assignment.StartDate }} {{ Assignment.StartTime }} </h4>
         <h4> DeadLine : {{ Assignment.DeadLineDate }} {{ Assignment.DeadLineTime }} </h4>
      </div>
    </div>
   {% endfor %}
</p>
{% else %}
   <p>No Assignments are available.</p>
{% endif %}
</div>
<p style="margin-top: 5em;">&nbsp;</p>

{% endblock %}

getSchedGo/getSchedGo/Timetable/templates/EventList.html
{% extends 'base.html'%}
{% block otherinclusions %}
<link href='https://fonts.googleapis.com/css?family=Alegreya SC' rel='stylesheet'>
{% endblock %}
{% block styles %}
<style type="text/css">
  .affix {
    top:50px;
    position: fixed;
    width: 100%;
    margin-left: 0;
    z-index: 1 !important;
  }
  .navbar {
      margin-bottom: 0px;
  }
</style>
{% endblock %}
{% block bars %}
<div align="center">Hi {{ user }}</div>
<nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="40">
 <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mynavbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

<div id="mynavbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'Timetable:SortEvent' 0 %}">Sort by ID</a></li>
          <li><a href="{% url 'Timetable:SortEvent' 1 %}">Sort by DATE</a></li>
          <li class="dropdown" align="right">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Filters <span class="caret"></span></a>
              <ul class="dropdown-menu">
<!-- using if for different view if user is logged in or not -->
                <li><a href="{% url 'Timetable:SortEvent' 2 %}">Scheduled Events</a></li>
                <li><a href="{% url 'Timetable:SortEvent' 3 %}">Unscheduled Events</a></li>
                <li><a href="{% url 'statistics:CompletedList' %}">Completed Events</a></li>
                <li><a href="{% url 'Timetable:SortEvent' 4%}">Pending Events</a></li>
                <li><a href="{% url 'Timetable:EventList' %}">All Events</a></li>
<!--                 <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li> -->
              </ul>
            </li>
        </ul>
      </div>

  </div>
</nav>
{% endblock %}

{% block content %}<!-- Using extend everything to be displayed are kept in extend.
It is just as if part of content in block of actually in base.html -->
<style type="text/css">

</style>
<script type="text/javascript">
  function show(id) {
    document.getElementById(id).style.display = "block";
  }
  function hide(id) {
    document.getElementById(id).style.display = "none";
  }
</script>



  {% if List %}
<p>
   {% for Event in List %}
   {% if Event.ScheduledStartTime %}
   <div onMouseOver="show('disc{{ Event.id }}')" onMouseOut="hide('disc{{ Event.id }}')" class="row event-holder" id="event{{ forloop.counter }}" style="background-color: white; color:#033a22; font-family: 'Alegreya SC';font-size: 24px;">
   {% else %}
   <div onMouseOver="show('disc{{ Event.id }}')" onMouseOut="hide('disc{{ Event.id }}')" class="row event-holder" id="event{{ forloop.counter }}" style="font-family: 'Alegreya SC';font-size: 24px;">
   {% endif %}    <div class="col-md-8">
         <h3> {{ Event.name }} </h3>
         <h4> From : {{Event.StartDate }} {{ Event.StartTime }} </h4>
         <h4> To : {{ Event.EndDate  }} {{ Event.EndTime }} </h4>
         {% if Event.TimeSettings != "B" %}
         <h4> DeadLine : {{ Event.DeadLineDate }} {{ Event.DeadLineTime }} </h4>
         {% endif %}
         {% if Event.ScheduledStartTime %}
         <h4> Scheduled from {{ Event.ScheduledStartTime }} to {{ Event.ScheduledEndTime }}</h4>
         {% endif %}
         <div id="disc{{ Event.id }}" style="display: none;">
           {{ Event.Description }}
         </div>
      </div>
      <div class="col-md-4" >
         <a href="{% url 'Timetable:EditEvent' Event.id %}"><span class="glyphicon glyphicon-edit shaker"></span></a>
         <a href="{% url 'Timetable:DeleteEvent' Event.id %}"><span class="glyphicon glyphicon-trash shaker"></span></a><br>
         {% if Event.ScheduledStartTime %}
         <a href="{% url 'Timetable:DescheduleEvent' Event.id %}" class="shaker"><span class="glyphicon glyphicon-calendar"></span><span class="glyphicon glyphicon-remove-sign"></a>
         {% endif %}
      </div>
    </div>
   {% endfor %}
</p>
{% else %}
   <p>No Events are available.</p>
{% endif %}
</div>
<p style="margin-top: 5em;">&nbsp;</p>

{% endblock %}

getSchedGo/getSchedGo/Timetable/templates/Eventtemplate.html
Hbsvjadbjb

getSchedGo/getSchedGo/Timetable/templates/class.html
{% extends 'base.html'%}
{% block otherinclusions %}
<link href='https://fonts.googleapis.com/css?family=Alegreya SC' rel='stylesheet'>
{% endblock %}
{% block styles %}
<style type="text/css">
  .affix {
    top:50px;
    position: fixed;
    width: 100%;
    margin-left: 0;
    z-index: 1 !important;
  }
  .navbar {
      margin-bottom: 0px;
  }
</style>
{% endblock %}
{% block bars %}
<div align="center">Hi {{ user }}</div>
<nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="40">
 <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mynavbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div id="mynavbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          <li><a href="{% url 'Timetable:SortClass' 0 %}">Sort by ID</a></li>
          <li><a href="{% url 'Timetable:SortClass' 1 %}">Sort by DATE</a></li>
        </ul>
      </div>

  </div>
</nav>
{% endblock %}

{% block content %}<!-- Using extend everything to be displayed are kept in extend.
It is just as if part of content in block of actually in base.html -->




  {% if List %}
<p>
   {% for Class in List %}
   <div class="row event-holder" id="event{{ forloop.counter }}" style="font-family: 'Alegreya SC';font-size: 24px;">
   <div class="col-md-8">
         <h3> {{ Class.name }} </h3>
         <h4> On : {{Class.Date }} </h4>
         <h4> From {{ Class.StartTime }} To {{ Class.EndTime }} </h4>
         <h4> At : {{ Class.Venue }} </h4>
      </div>

    </div>
   {% endfor %}
</p>
{% else %}
   <p>No Classes are available.</p>
{% endif %}
</div>
<p style="margin-top: 5em;">&nbsp;</p>

{% endblock %}

getSchedGo/getSchedGo/Timetable/templates/exam.html
{% extends 'base.html'%}
{% block otherinclusions %}
<link href='https://fonts.googleapis.com/css?family=Alegreya SC' rel='stylesheet'>
{% endblock %}
{% block styles %}
<style type="text/css">
  .affix {
    top:50px;
    position: fixed;
    width: 100%;
    margin-left: 0;
    z-index: 1 !important;
  }
  .navbar {
      margin-bottom: 0px;
  }
</style>
{% endblock %}
{% block bars %}
<div align="center">Hi {{ user }}</div>
<nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="40">
 <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mynavbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div id="mynavbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          <li><a href="{% url 'Timetable:SortExam' 0 %}">Sort by ID</a></li>
          <li><a href="{% url 'Timetable:SortExam' 1 %}">Sort by DATE</a></li>
        </ul>
      </div>

  </div>
</nav>
{% endblock %}

{% block content %}<!-- Using extend everything to be displayed are kept in extend.
It is just as if part of content in block of actually in base.html -->




  {% if List %}
<p>
   {% for Exam in List %}
   <div class="row event-holder" id="event{{ forloop.counter }}" style="font-family: 'Alegreya SC';font-size: 24px;">
   <div class="col-md-8">
         <h3> {{ Exam.name }} </h3>
         <h4> On : {{Exam.Date }} </h4>
         <h4> From {{ Exam.StartTime }} To {{ Exam.EndTime }} </h4>
         <h4> At : {{ Exam.Venue }} </h4>
         <h4> Preparation : {{ Exam.PreparationDuration }}
      </div>

    </div>
   {% endfor %}
</p>
{% else %}
   <p>No Exams are available.</p>
{% endif %}
</div>
<p style="margin-top: 5em;">&nbsp;</p>

{% endblock %}

getSchedGo/getSchedGo/Timetable/templates/suggestion.html
{% load crispy_forms_tags %}

{% block content %}

<div align="center">Hi {{ user }}</div>

<div class="col-md-8 col-md-offset-2">

	 <form method="post">
			{% csrf_token %}<!-- Must in forms. Extra object for cyber Site cross referencing object -->
			{% for field in form %}<!-- making a loop across form to break it into 2-3 forms -->
				{{ field|as_crispy_field }}
				
			{% endfor %}
			<br>
			<button type="submit">Submit</button>
		</form>
</div>
{% endblock %}