getSchedGo/getSchedGo/Event_suggestion/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
app_name = 'suggestion'
## The URL list from suggestion
# @details these url are when called followed by appname:urlname
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r"^(?P<pk>[0-9]+)/eventconversion$", views.ConvertToEvent, name="ConvertToEvent"),


]
# ^(?P<pk>[0-9]+)/edit$
   

getSchedGo/getSchedGo/Timetable/urls.py
from django.conf.urls import url
from . import views
app_name = 'Timetable'
urlpatterns = [
    url(r"^$", views.EventList, name="EventList"),
    url(r"^create/$", views.CreateEvent, name="CreateEvent"),
    url(r"^(?P<pk>[0-9]+)/edit$", views.CreateEvent, name="EditEvent"),
    url(r"^(?P<pk>[0-9]+)/delete$", views.DeleteEvent, name="DeleteEvent"),
    url(r"^(?P<pk>[0-9]+)/desched$", views.DescheduleEvent, name="DescheduleEvent"),
    url(r"^(?P<pk>[0-9]+)/sort$", views.EventList, name="SortEvent"),
    url(r"^CreateAssignment$", views.CreateAssignment, name="CreateAssignment"),
    url(r"^Assignments$", views.Assignments, name="AssignmentList"),
    url(r"^(?P<pk>[0-9]+)/SortAssignment$", views.Assignments, name="SortAssignment"),
    url(r"^CreateClass$", views.CreateClass, name="CreateClass"),
    url(r"^Classes$", views.Classes, name="ClassList"),
    url(r"^(?P<pk>[0-9]+)/SortClass$", views.Classes, name="SortClass"),
    url(r"^CreateExam$", views.CreateExam, name="CreateExam"),
    url(r"^Exams$", views.Exams, name="ExamList"),
    url(r"^(?P<pk>[0-9]+)/SortExam$", views.Exams, name="SortExam"),
    url(r'^today/$',views.Schedules, name = "Schedule"),
   
]

getSchedGo/getSchedGo/courses/urls.py
from django.conf.urls import url
from . import views
## name of app to call it's url without clash with other app's url. works as a namespaces
app_name = 'courses'
## list of all url's corresponding to type of get requests to access all the view 
urlpatterns = [
    url(r"^$", views.CourseView, name="CourseView"),
    url(r"^some/(?P<pk1>[a-zA-Z0-9_ ]+)/(?P<pk2>\w+)/$", views.CourseView, name="some"),
    url(r"^list/$",views.Enrollmentview, name="Enrollmentview"),
    url(r"^(?P<pk>[0-9]+)/add/$",views.UserAdder, name="UserAdder"),
    url(r"^(?P<pk>[0-9]+)/remove/$",views.UserDropper, name="UserDropper"),
    # url(r"^(?P<pk>[0-9]+)/anyDay/$", views.TodayStats, name="AnyDayStatistics"),
    # url(r"^list/$", views.EventBeforeDate, name="EventBeforeDate"),
    # url(r"^donelist/$", views.CompletedList, name="CompletedList"),
    # url(r"^(?P<pk>[0-9]+)/comp/$", views.MarkItCompleted, name="MarkItCompleted"),
    url(r"^EditCourse$", views.EditCourse, name="EditCourse"),
    url(r"^SelectCourse$", views.SelectCourse, name="SelectCourse"),
    url(r"^(?P<pk>[0-9]+)/ClaimCourse$", views.SelectCourse, name="ClaimCourse"),
    url(r"^(?P<pk>[0-9]+)/converttoevent$", views.AssignmentToEvent, name="AssignmentToEvent"),
    url(r"^(?P<pk>[0-9]+)/classtoevent$", views.ClassToEvent, name="ClassToEvent"),
    url(r"^(?P<pk>[0-9]+)/examtoevent$", views.ExamToEvent, name="ExamToEvent"),
    url(r"^(?P<pk>[0-9]+)/examppreptoevent$", views.ExamPrepToEvent, name="ExamPrepToEvent"),

]

getSchedGo/getSchedGo/getSchedGo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

from profiles import views as profiles_views
# from courses import views as course_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', profiles_views.home, name='home'),
    url(r'^about/$', profiles_views.about, name='about'),
    url(r'^profile/$', profiles_views.userProfile, name='profile'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^event/', include('Timetable.urls')),
    url(r'^stats/', include('statistics.urls')),
    url(r'^course/', include('courses.urls')),
    url(r'^suggestion/', include('Event_suggestion.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

getSchedGo/getSchedGo/statistics/urls.py
from django.conf.urls import url
from . import views
## app_name helps django index urls mentioned below and for calling
# these urls is app_name:urlName. this helps developers forget the name they might have given
# to an app in different app 
app_name = 'statistics'
## These are list urlPatterns for this app. Ones containing 
# pk are the ones carrying parameters to corresponding view to do something specific
# for different call of same view with different parameters
urlpatterns = [
    url(r"^$", views.TodayStats, name="TodayStatistic"),
    url(r"^(?P<pk>[0-9]+)/anyDay/$", views.TodayStats, name="AnyDayStatistics"),
    url(r"^list/$", views.EventBeforeDate, name="EventBeforeDate"),
    url(r"^donelist/$", views.CompletedList, name="CompletedList"),
    url(r"^(?P<pk>[0-9]+)/comp/$", views.MarkItCompleted, name="MarkItCompleted"),
    url(r"^csvlist/$", views.AheadOfTime, name="AheadOfTime"),
    url(r"^google/$",views.googleConnector, name="googleConnector")
    
]

getSchedGo/getSchedGo/profiles/models.py
from django.db import models
from django.conf import settings
# from Timetable.models import DailySched, Slots
from allauth.account.signals import user_logged_in, user_signed_up
from datetime import *
from Timetable.slots import SlotPattern as sp
from Timetable.slotconverter import slotInterval
## This was a hack to make sure that the suggestion for football was refreshed only after certain time
d=date.today()-timedelta(days=5)
# Create your models here.
## Choices for models for the choicefield
STUDY_CHOICES = [('1','Day'), ('3','Night'), ('4','Late Night')]
## Choices for models for the choicefield
SLEEP_TIME = [('A','6 hours'), ('B','7 hours'), ('C','8 hours')]

## Profile model is a model connected to every user
# @details This stores extra data we expect as input from user to give a better schedule
# Things from this can be used to store preferences of user as a model
class profile(models.Model):
	#Basic Model that holds user data
	name = models.CharField(max_length=120)
	#Various Fields for user preference.
	studyChoice = models.CharField(max_length=1,choices=STUDY_CHOICES,default='3')
	sleepChoice = models.CharField(max_length=1,choices=SLEEP_TIME,default='B')
	# crickenthu = models.BooleanField(default=False,)
	# NBAenthu = models.BooleanField(default=False,)
	# footballenthu = models.BooleanField(default=False,)
	## connection with oneToOne relation to user
	user = models.OneToOneField(settings.AUTH_USER_MODEL, null=True, blank = True)
	## Is the user an instructor and then provide special features to him
	instructor = models.BooleanField(default=False, blank = True)
	## stores when was last FootBall API was called and hence when to call Next
	lastSuggestion = models.DateField(null=True, default = d)
	#connects to User model


	# What to display as index in admin page use __unicode__ for python2
	def __str__(self):
		return self.name
## function that creates profile model when called schedule model is created  along with creating all the 48 slot for every day
def createSched(Day,userProfile,user):
	from Timetable.models import DailySched, Slots, Event
	from Timetable.schedule import fixedScheduleAdder
	from statistics.models import dailyStats
	from courses.models import coursedetail
	Sched_today, wasCreated = DailySched.objects.get_or_create(UserProfile=userProfile,Active_day = Day)
	## if creation of object was at the time of call, fill it with slots
	if wasCreated:
		Sched_today.name = "Primary"+str(Sched_today.Active_day)
		Sched_today.save()
		DayStat = dailyStats(linkedDay = Sched_today,)
		DayStat.save()
		for i in range(1,49):
			k = (i-1)%2
			mins = (k)*30
			hour = (i-1)//2
			mins_e = ((k+1)%2)*30
			hour_e = (i//2)%24
			Slotx = Slots(UserProfile = userProfile, Day_Sched = Sched_today,
			StartTime = str(hour)+":"+str(mins)+":"+"00", EndTime = str(hour_e)+":"+str(mins_e)+":"+"00", SlotNum = i)
			Slotx.save()
		WEEKDAY = Day.weekday()+1
		CourseList = coursedetail.objects.filter(Student = userProfile)
		for course in CourseList:
			slots = course.Slot
			slots = slots.split(" ")
			slots.pop()
			for s in slots:
				d,st,et = slotInterval(sp[s])
				if d == str(WEEKDAY):
					st=st.split(":")
					et=et.split(":")
					st = time(int(st[0]),int(st[1]),int(st[2]))
					et = time(int(et[0]),int(et[1]),int(et[2]))
					stu = Event(UserProfile = userProfile,name = course.name+" Class",
					 StartTime = st, StartDate = Day, TimeSettings = 'B',
					 EndTime = et, EndDate = Day, Priority = '4', Type='A')
					stu.save()
					fixedScheduleAdder(stu,user)
## my_Call is a function which is called when user logs in
# if profile is created then assign profile name as user name
# Call createsched to create or check if created for next 3 days
def my_Call(sender, request, user, **kwargs):
	from Timetable.models import DailySched, Slots
	userProfile, isCreated = profile.objects.get_or_create(user=user)
	if isCreated:
		userProfile.name = user.username
		userProfile.save()
	for i in range(4):
		createSched(date.today()+timedelta(days=i),userProfile,user)
## To execute mycall at login
user_logged_in.connect(my_Call)


class FeedBack(models.Model):
	Name= models.CharField(max_length=120)
	Email=models.EmailField(blank=True)
	contact=models.IntegerField(null=True)
	Description= models.CharField(max_length=300)

getSchedGo/getSchedGo/profiles/forms.py
from django import forms
from .models import profile
from  .models import FeedBack

## A tuple made for choice. First value will be stored in database. Second will be key to Display
STUDY_CHOICES = [('1','Day'), ('3','Night'), ('4','Late Night')]
## A tuple made for choice. First value will be stored in database. Second will be key to Display
SLEEP_TIME = [('A','6 hours'), ('B','7 hours'), ('C','8 hours')]
## A model form that through meta get linked to profile imported from .models
# This model form is a class that gets displayed as a form in html and ask entry from user
class SimpleForm(forms.ModelForm):
	name = forms.CharField(max_length=120)
	studyChoice = forms.ChoiceField(
		required = True,
		widget = forms.RadioSelect,
		choices  = STUDY_CHOICES,)
	sleepChoice = forms.ChoiceField(
		widget = forms.RadioSelect,
		choices = SLEEP_TIME)
	# crickenthu = forms.BooleanField(required=False,label='Suggestions for cricket matches')
	# NBAenthu = forms.BooleanField(required=False,label='Suggestions for NBA matches')
	# footballenthu = forms.BooleanField(required=False,label='Suggestions for football matches')
	instructor = forms.BooleanField(required = False,label = 'Are you an Instructor')
	class Meta:
		model = profile
		fields = ('name','studyChoice','sleepChoice','instructor')


class FeedBackForm(forms.ModelForm):
	class Meta:
		model= FeedBack
		exclude=('contact',)
		widgets = {
		'Description': forms.Textarea(attrs={'placeholder': 'Enter description here'}),
		}

getSchedGo/getSchedGo/profiles/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import SimpleForm,FeedBackForm
from .models import profile,FeedBack
# Create your views here.
# main page url is ^$. No special context to be displayed

## This view is the home of the web app.
# @details Most data displayed is static and hence a blank context is passed.
# template home.html uses django html parsing tricks to achieve different 
# content to different users.
def home(request):
	context = {}
	template = 'home.html'
	return render(request,template,context)

## A view that would brief user about the application
def about(request):
	user = request.user
	## When Submit is pressed
	if request.method == "POST":
		form = FeedBackForm(request.POST)
		form.save()
	context = {'FeedBackForm':FeedBackForm}
	template = 'about.html'
	return render(request,template,context)

## This view asks user to fill profile details
# @details This view uses the form created in form.py instanciated with current 
# profile of user and asks user to fill/ change the values
# If user submits the form, it redirects to the same view with a post request
# that post request is saved which edits the value of fields of user's profile 
# in database
# login_required cap is added to ensure that 
# Anything below this redirects to accounts/login if user is not authenticated
@login_required 
def userProfile(request):
	user = request.user
	#context = {'user': user,}
	template = 'profile.html'
	if request.method == 'POST':
		form=SimpleForm(request.POST, instance=request.user.profile)
		if form.is_valid():
			form.save()
			return redirect('home')
		# form = SimpleForm(request.POST)
		# if form.is_valid():
		#   pos = form.save(commit=False)
		#   pos.user = request.user
		#   # userProfile, isCreated = profile.objects.get_or_create(user=user)
		#   update_prof=profile.objects.get(user=user)
		#   update_prof=pos
		#   update_prof.save()
		#   form = SimpleForm()
		#   return redirect('home')
		return render(request,template,{'user': user, 'form': form})

	else: #for get request i.e. when page opens on browser
		form = SimpleForm(instance=user.profile) #fills choice from earlier user data is Db
		return render(request,template,{'user': user, 'form': form})

getSchedGo/getSchedGo/profiles/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="shortcut icon" type="image/png" href="{% static 'img/icon.png' %}">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
<!--     <link rel="icon" href="../../favicon.ico">
 -->
    <title>GetSchedGo</title>

    <!-- Bootstrap core CSS -->
    <link href='{% static "css/bootstrap.min.css" %}' rel="stylesheet" >
    <!-- Bootstrap theme -->
    <link href='{% static "css/bootstrap-theme.min.css" %}' rel="stylesheet" >
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
 -->
    <!-- Custom styles for this template -->
    <link href='{% static "css/theme.css" %}' rel="stylesheet" >
    <link href='{% static "css/main.css" %}' rel="stylesheet" >
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
 -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block otherinclusions %}
    {% endblock %}
  </head>

  <body>

    <!-- Fixed navbar -->
 {% include 'navbar.html' %}
{% block styles %}
{% endblock %}
{% block bars %}
{% endblock %}
    <div class="container theme-showcase" role="main">

{% block jbtron %}
{% endblock %}
{% block content %}
{% endblock %}
      <!-- Main jumbotron for a primary marketing message or call to action -->






    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://js.stripe.com/v2/"></script>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
     --><script src='{% static "javascript/bootstrap.min.js" %}'></script>
    <script src='{% static "javascript/docs.min.js" %}'></script>
    <script src='{% static "javascript/bootbox.min.js" %}'></script>
    <script src='{% static "javascript/jquery.validate.js" %}'></script>
    {% block jscript %}
    {% endblock %}
<!--     <script>
        $(document).ready(function(){
});
    </script> -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!--     <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
 -->  </body>
</html>

getSchedGo/getSchedGo/profiles/templates/navbar.html
<style type="text/css">
.navbar-default {
  background-color: #bdd6ec;
  border-color: #97e5f7;
}
.navbar-default .navbar-brand {
  color: #3c3f3f;
}
.navbar-default .navbar-brand:hover,
.navbar-default .navbar-brand:focus {
  color: #636e09;
}
.navbar-default .navbar-text {
  color: #3c3f3f;
}
.navbar-default .navbar-nav > li > a {
  color: #3c3f3f;
}
.navbar-default .navbar-nav > li > a:hover,
.navbar-default .navbar-nav > li > a:focus {
  color: #636e09;
}
.navbar-default .navbar-nav > li > .dropdown-menu {
  background-color: #bdd6ec;
}
.navbar-default .navbar-nav > li > .dropdown-menu > li > a {
  color: #3c3f3f;
}
.navbar-default .navbar-nav > li > .dropdown-menu > li > a:hover,
.navbar-default .navbar-nav > li > .dropdown-menu > li > a:focus {
  color: #636e09;
  background-color: #97e5f7;
}
.navbar-default .navbar-nav > li > .dropdown-menu > li.divider {
  background-color: #97e5f7;
}
.navbar-default .navbar-nav .open .dropdown-menu > .active > a,
.navbar-default .navbar-nav .open .dropdown-menu > .active > a:hover,
.navbar-default .navbar-nav .open .dropdown-menu > .active > a:focus {
  color: #636e09;
  background-color: #97e5f7;
}
.navbar-default .navbar-nav > .active > a,
.navbar-default .navbar-nav > .active > a:hover,
.navbar-default .navbar-nav > .active > a:focus {
  color: #636e09;
  background-color: #97e5f7;
}
.navbar-default .navbar-nav > .open > a,
.navbar-default .navbar-nav > .open > a:hover,
.navbar-default .navbar-nav > .open > a:focus {
  color: #636e09;
  background-color: #97e5f7;
}
.navbar-default .navbar-toggle {
  border-color: #97e5f7;
}
.navbar-default .navbar-toggle:hover,
.navbar-default .navbar-toggle:focus {
  background-color: #97e5f7;
}
.navbar-default .navbar-toggle .icon-bar {
  background-color: #3c3f3f;
}
.navbar-default .navbar-collapse,
.navbar-default .navbar-form {
  border-color: #3c3f3f;
}
.navbar-default .navbar-link {
  color: #3c3f3f;
}
.navbar-default .navbar-link:hover {
  color: #636e09;
}

@media (max-width: 767px) {
  .navbar-default .navbar-nav .open .dropdown-menu > li > a {
    color: #3c3f3f;
  }
  .navbar-default .navbar-nav .open .dropdown-menu > li > a:hover,
  .navbar-default .navbar-nav .open .dropdown-menu > li > a:focus {
    color: #636e09;
  }
  .navbar-default .navbar-nav .open .dropdown-menu > .active > a,
  .navbar-default .navbar-nav .open .dropdown-menu > .active > a:hover,
  .navbar-default .navbar-nav .open .dropdown-menu > .active > a:focus {
    color: #636e09;
    background-color: #97e5f7;
  }
}
</style>
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home'%}">GetSchedGo</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          {% url 'home' as home %}<!-- making local variable -->
          {% url 'profile' as profile %}
          {% url 'about' as about %}
          {% url 'statistics:TodayStatistic' as statsHome %}
          <li {% if request.path == home %} class="active"{% endif %}><a href="{% url 'home'%}">Home</a></li><!-- Turns to active in navbar if current path is home -->
          <li {% if request.path == profile %} class="active"{% endif %}><a href="{% url 'profile'%}">Profile</a></li>
          
          <li {% if request.path == statsHome %} class="active"{% endif %}><a href="{% url 'statistics:TodayStatistic'%}">Statistics</a></li>

            {% if request.user.is_authenticated %}
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Events<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'Timetable:CreateEvent'%}">Add Events</a></li>
                <li><a href="{% url 'Timetable:EventList'%}">Event List</a></li>
                <li><a href="{% url 'Timetable:Schedule'%}">TimeTable</a></li>
                <li><a href="{% url 'suggestion:index'%}">Suggested Events</a></li>
                <li><a href="{% url 'statistics:EventBeforeDate' %}">Event Feedback</a>
              </ul>
            </li>
            {% url 'statistics:googleConnector' as googl%}
<li  {% if request.path == googl %} class="active"{% endif %}>        <a href="{% url 'statistics:googleConnector' %}"><img src="https://calendar.google.com/googlecalendar/images/favicon_v2014_18.ico" width="30" height="25"></a>
</li>
            {% if request.user.profile.instructor %}
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Create Student Event<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'Timetable:CreateAssignment'%}">Add Assignment</a></li>
                <li><a href="{% url 'Timetable:CreateClass'%}">Add Class</a></li>
                <li><a href="{% url 'Timetable:CreateExam'%}">Add Exam</a></li>
                <li><a href="{% url 'Timetable:AssignmentList'%}">Assignments</a></li>
                <li><a href="{% url 'Timetable:ClassList'%}">Class</a></li>
                <li><a href="{% url 'Timetable:ExamList'%}">Exam</a></li>
              </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Courses<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'courses:SelectCourse'%}">Select Course</a></li>
                <li><a href="{% url 'courses:EditCourse'%}">View/Edit Course</a></li>
              </ul>
            </li>
            {% else %}
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Courses<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'courses:CourseView'%}">My Course</a></li>
                <li><a href="{% url 'courses:Enrollmentview'%}">Enroll for Course</a></li>
              </ul>
            </li>
            {% endif %}
            {% endif %}
            <li {% if request.path == about %} class="active"{% endif %}><a href="{% url 'about'%}">FAQ</a></li>
            
             <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                {% if not request.user.is_authenticated %}<!-- using if for different view if user is logged in or not -->
                <li><a href="{% url 'account_login'%}">Login</a></li>
                <li><a href="{% url 'account_signup'%}">Signup</a></li>
                {% else %}
                <li><a href="{% url 'account_logout'%}">Logout</a></li>
                {% endif %}
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>