getSchedGo/getSchedGo/Timetable/urls.py
from django.conf.urls import url
from . import views
app_name = 'Timetable'
urlpatterns = [
    url(r"^$", views.EventList, name="EventList"),
    url(r"^create/$", views.CreateEvent, name="CreateEvent"),
    url(r"^(?P<pk>[0-9]+)/edit$", views.CreateEvent, name="EditEvent"),
    url(r"^(?P<pk>[0-9]+)/delete$", views.DeleteEvent, name="DeleteEvent"),
    url(r"^(?P<pk>[0-9]+)/desched$", views.DescheduleEvent, name="DescheduleEvent"),
    url(r"^(?P<pk>[0-9]+)/sort$", views.EventList, name="SortEvent"),
    url(r"^CreateAssignment$", views.CreateAssignment, name="CreateAssignment"),
    url(r"^Assignments$", views.Assignments, name="AssignmentList"),
    url(r"^(?P<pk>[0-9]+)/SortAssignment$", views.Assignments, name="SortAssignment"),
    url(r"^CreateClass$", views.CreateClass, name="CreateClass"),
    url(r"^Classes$", views.Classes, name="ClassList"),
    url(r"^(?P<pk>[0-9]+)/SortClass$", views.Classes, name="SortClass"),
    url(r"^CreateExam$", views.CreateExam, name="CreateExam"),
    url(r"^Exams$", views.Exams, name="ExamList"),
    url(r"^(?P<pk>[0-9]+)/SortExam$", views.Exams, name="SortExam"),
    url(r'^today/$',views.Schedules, name = "Schedule"),
   
]

getSchedGo/getSchedGo/courses/urls.py
from django.conf.urls import url
from . import views
## name of app to call it's url without clash with other app's url. works as a namespaces
app_name = 'courses'
## list of all url's corresponding to type of get requests to access all the view 
urlpatterns = [
    url(r"^$", views.CourseView, name="CourseView"),
    url(r"^some/(?P<pk1>[a-zA-Z0-9_ ]+)/(?P<pk2>\w+)/$", views.CourseView, name="some"),
    url(r"^list/$",views.Enrollmentview, name="Enrollmentview"),
    url(r"^(?P<pk>[0-9]+)/add/$",views.UserAdder, name="UserAdder"),
    url(r"^(?P<pk>[0-9]+)/remove/$",views.UserDropper, name="UserDropper"),
    # url(r"^(?P<pk>[0-9]+)/anyDay/$", views.TodayStats, name="AnyDayStatistics"),
    # url(r"^list/$", views.EventBeforeDate, name="EventBeforeDate"),
    # url(r"^donelist/$", views.CompletedList, name="CompletedList"),
    # url(r"^(?P<pk>[0-9]+)/comp/$", views.MarkItCompleted, name="MarkItCompleted"),
    url(r"^EditCourse$", views.EditCourse, name="EditCourse"),
    url(r"^SelectCourse$", views.SelectCourse, name="SelectCourse"),
    url(r"^(?P<pk>[0-9]+)/ClaimCourse$", views.SelectCourse, name="ClaimCourse"),
    url(r"^(?P<pk>[0-9]+)/converttoevent$", views.AssignmentToEvent, name="AssignmentToEvent"),
    url(r"^(?P<pk>[0-9]+)/classtoevent$", views.ClassToEvent, name="ClassToEvent"),
    url(r"^(?P<pk>[0-9]+)/examtoevent$", views.ExamToEvent, name="ExamToEvent"),
    url(r"^(?P<pk>[0-9]+)/examppreptoevent$", views.ExamPrepToEvent, name="ExamPrepToEvent"),

]

getSchedGo/getSchedGo/getSchedGo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

from profiles import views as profiles_views
# from courses import views as course_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', profiles_views.home, name='home'),
    url(r'^about/$', profiles_views.about, name='about'),
    url(r'^profile/$', profiles_views.userProfile, name='profile'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^event/', include('Timetable.urls')),
    url(r'^stats/', include('statistics.urls')),
    url(r'^course/', include('courses.urls')),
    url(r'^suggestion/', include('Event_suggestion.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

getSchedGo/getSchedGo/statistics/urls.py
from django.conf.urls import url
from . import views
## app_name helps django index urls mentioned below and for calling
# these urls is app_name:urlName. this helps developers forget the name they might have given
# to an app in different app 
app_name = 'statistics'
## These are list urlPatterns for this app. Ones containing 
# pk are the ones carrying parameters to corresponding view to do something specific
# for different call of same view with different parameters
urlpatterns = [
    url(r"^$", views.TodayStats, name="TodayStatistic"),
    url(r"^(?P<pk>[0-9]+)/anyDay/$", views.TodayStats, name="AnyDayStatistics"),
    url(r"^list/$", views.EventBeforeDate, name="EventBeforeDate"),
    url(r"^donelist/$", views.CompletedList, name="CompletedList"),
    url(r"^(?P<pk>[0-9]+)/comp/$", views.MarkItCompleted, name="MarkItCompleted"),
    url(r"^csvlist/$", views.AheadOfTime, name="AheadOfTime"),
    url(r"^google/$",views.googleConnector, name="googleConnector")
    
]

getSchedGo/getSchedGo/statistics/models.py
from django.db import models
from Timetable.models import DailySched

# Create your models here.
## dailyStats is a django model developed for storing data of a given day of a 
# given user
# @details For this, it follows a oneToOne relation with a dailySched model and stores data of 
# time given to all seperate event type and out of those one that are completed
class dailyStats(models.Model):
	linkedDay = models.OneToOneField(DailySched,null=True, blank = True)
	SelfStudy = models.IntegerField(default = 0)
	ExtraCurricularsTime = models.IntegerField(default = 0)
	ExtraStudyTime = models.IntegerField(default = 0)
	ClassTiming = models.IntegerField(default = 0)
	MiscellaneousTime = models.IntegerField(default = 0)
	CompletedSelfStudy = models.IntegerField(default = 0)
	CompletedExtraCurricularsTime = models.IntegerField(default = 0)
	CompletedExtraStudyTime = models.IntegerField(default = 0)
	CompletedClassTiming = models.IntegerField(default = 0)
	CompletedMiscellaneousTime = models.IntegerField(default = 0)

getSchedGo/getSchedGo/statistics/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from Timetable.models import DailySched, Event, Slots
from .models import *
from datetime import datetime , timedelta, date
from django.db.models import Q
from django.views.static import serve
import os
import re
# Create your views here.

## TodayStats is the basic statistics view which displays what user has done over past days
# @param request basic call for a view in django
# @param pk contains key for whether asked statistics of yesterday or today 
# @details This supplies a dictionary filled with data to basicStatistics.html which displays to user all his data over past days
# depending of selection from dropdown list available on html page
#
# Also there is a call for function updateStats to recalculate number of scheduled and completed slots over that day.
# All the calculation of percentage for statistics display is gone in this view itself
@login_required
def TodayStats(request,pk=-1):
	if pk=='1' :
		Today=date.today() - timedelta(days = 1)
	elif pk == '2':
		Today=date.today() - timedelta(days = 2)
	else :
		Today=date.today()
	user = request.user
	from profiles.models import createSched
	createSched(Today,user.profile,user)
	TodaySched = get_object_or_404(DailySched,UserProfile =user.profile,Active_day=Today)
	TodaysStats = get_object_or_404(dailyStats,linkedDay = TodaySched)
	updateStats(TodaysStats)
	#make the calculation for data display here
	if TodaysStats.SelfStudy != 0 :
		ScheduledCompletedSelfStudy = TodaysStats.CompletedSelfStudy * 100 / TodaysStats.SelfStudy
		print(ScheduledCompletedSelfStudy )
	else :
		ScheduledCompletedSelfStudy = None
	if TodaysStats.ClassTiming != 0 :
		ScheduledCompletedClassTiming = TodaysStats.CompletedClassTiming * 100 / TodaysStats.ClassTiming
	else :
		ScheduledCompletedClassTiming = None
	if TodaysStats.ExtraStudyTime != 0 :
		ScheduledCompletedExtraStudyTime = TodaysStats.CompletedExtraStudyTime * 100 / TodaysStats.ExtraStudyTime
	else :
		ScheduledCompletedExtraStudyTime = None
	if TodaysStats.MiscellaneousTime != 0 :
		ScheduledCompletedMiscellaneousTime = TodaysStats.CompletedMiscellaneousTime * 100 / TodaysStats.MiscellaneousTime
	else :
		ScheduledCompletedMiscellaneousTime = None
	if TodaysStats.ExtraCurricularsTime != 0 :
		ScheduledCompletedExtraCurricularsTime = TodaysStats.CompletedExtraCurricularsTime * 100 / TodaysStats.ExtraCurricularsTime
	else :
		ScheduledCompletedExtraCurricularsTime = None

	PercentageSelfStudy = (TodaysStats.SelfStudy * 100) // 48
	PercentageExtraCurricularsTime = (TodaysStats.ExtraCurricularsTime * 100) // 48
	PercentageExtraStudyTime = (TodaysStats.ExtraStudyTime * 100) // 48
	PercentageClassTiming = (TodaysStats.ClassTiming * 100) // 48
	PercentageMiscellaneousTime  = (TodaysStats.MiscellaneousTime * 100) // 48
	TotalSchedTime = PercentageSelfStudy + PercentageExtraCurricularsTime + PercentageExtraStudyTime + PercentageClassTiming + PercentageMiscellaneousTime
	if TotalSchedTime != 0:
		RelativePercentageSelfStudy = PercentageSelfStudy * 100 // TotalSchedTime
		RelativePercentageExtraCurricularsTime = PercentageExtraCurricularsTime * 100 // TotalSchedTime
		RelativePercentageExtraStudyTime = PercentageExtraStudyTime * 100 // TotalSchedTime
		RelativePercentageClassTiming = PercentageClassTiming * 100 // TotalSchedTime
		RelativePercentageMiscellaneousTime  = PercentageMiscellaneousTime * 100 // TotalSchedTime
	else : 
		RelativePercentageSelfStudy = 0
		RelativePercentageExtraCurricularsTime = 0
		RelativePercentageExtraStudyTime = 0
		RelativePercentageClassTiming = 0
		RelativePercentageMiscellaneousTime = 0

		# PercentageSelfStudy = (TodaysStats.SelfStudy * 100) // 48 
	percentage = {'PercentageSelfStudy' : PercentageSelfStudy , 'PercentageExtraCurricularsTime' : PercentageExtraCurricularsTime , 'PercentageExtraStudyTime' : PercentageExtraStudyTime, 'PercentageClassTiming': PercentageClassTiming, 'PercentageMiscellaneousTime' : PercentageMiscellaneousTime, 'ScheduledCompletedSelfStudy' : ScheduledCompletedSelfStudy , 'ScheduledCompletedClassTiming' : ScheduledCompletedClassTiming , 'ScheduledCompletedExtraStudyTime' : ScheduledCompletedExtraStudyTime , 'ScheduledCompletedMiscellaneousTime' : ScheduledCompletedMiscellaneousTime , 'ScheduledCompletedExtraCurricularsTime': ScheduledCompletedExtraCurricularsTime , 'RelativePercentageSelfStudy' : RelativePercentageSelfStudy , 'RelativePercentageExtraCurricularsTime' : RelativePercentageExtraCurricularsTime , 'RelativePercentageExtraStudyTime' : RelativePercentageExtraStudyTime, 'RelativePercentageClassTiming': RelativePercentageClassTiming, 'RelativePercentageMiscellaneousTime' : RelativePercentageMiscellaneousTime, 'TotalSchedTime' : TotalSchedTime}
	#
	context = {'user': user,'TodaysStats': TodaysStats, 'percentage': percentage}
	print(TodaysStats.linkedDay.Active_day )
	template = 'basicStatistics.html'
	return render(request,template,context)

## EventBeforeDate is the  view which displays what all events that were scheduled to be done by user
# @param request basic call for a view in django
# @details This page in general displays all scheduled event whose end-Time is less than the current Time
# also with options to either mark it completed if user has done it or delete the event, or resvhedule them sometime in the future
#
# This view is the feedback system gets from the user about the user which helps application give proper statistics of the past 
# and efficiency of the user

@login_required
def EventBeforeDate(request):
	user = request.user
	List = Event.objects.filter(UserProfile=user.profile).exclude(ScheduledStartTime=None).filter(Q(EndDate__lt=datetime.today() ) | (Q(EndDate=datetime.today(),ScheduledEndTime__lte=datetime.today())))
	context = {'user': user , 'List': List}
	# print(List)
	template = 'basicfeedback.html'
	return render(request,template,context)

## AheadOfTime is the intermediate view which serves events of user as CSV
# @param request basic call for a view in django
# @details This view gets all events list scheduled to start after current time.
# This helps system generate a csv file of all these events 
#
# Further this csv file can be exported to any external calender app. 
# serving the file will download the file in user's local system which he can use further

@login_required
def AheadOfTime(request):
	user = request.user
	List = Event.objects.filter(UserProfile=user.profile).exclude(ScheduledStartTime=None).filter(Q(StartDate__gte=datetime.today()) | Q(StartDate=datetime.today(), ScheduledStartTime__gte=datetime.today()))
	# print(List)	
	temp = open("sched"+str(user)+".csv","w+")
	temp.write("Subject,Start Date,Start Time,End Date,End Time,All Day Event,Description,Location,Private \n")
	for event in List:
		if str(event.ScheduledEndTime) == '00:00:00' :
			temp.write(str(event.name))
			temp.write(",")
			temp.write(str(event.StartDate.month)+"/"+str(event.StartDate.day)+"/"+str(event.StartDate.year)) #eventDate may not be same as event scheduled date so that must be taken care of
			temp.write(",")
			temp.write(str(event.ScheduledStartTime))
			temp.write(",")
			temp.write(str(event.StartDate.month)+"/"+str(event.StartDate.day)+"/"+str(event.StartDate.year))
			temp.write(',"')
			temp.write('24:00:00')
			temp.write('",')
			temp.write('FALSE,"')
			temp.write(str(event.Description))
			temp.write('","')
			temp.write(str(event.Venue))
			temp.write('",TRUE')
			temp.write("\n")
		else:			
			temp.write(str(event.name))
			temp.write(",")
			temp.write(str(event.StartDate.month)+"/"+str(event.StartDate.day)+"/"+str(event.StartDate.year)) #eventDate may not be same as event scheduled date so that must be taken care of
			temp.write(",")
			temp.write(str(event.ScheduledStartTime))
			temp.write(",")
			temp.write(str(event.StartDate.month)+"/"+str(event.StartDate.day)+"/"+str(event.StartDate.year))
			temp.write(',"')
			temp.write(str(event.ScheduledEndTime))
			temp.write('",')
			temp.write('FALSE,"')
			temp.write(str(event.Description))
			temp.write('","')
			temp.write(str(event.Venue))
			temp.write('",TRUE')
			temp.write("\n")
	temp.close()
	filepath = "./sched"+str(user)+".csv"
	return serve(request, os.path.basename(filepath), os.path.dirname(filepath))
	#return redirect("statistics:EventBeforeDate")

## googleConnector is the  view which has link to view for generating CSV
# @param request basic call for a view in django
# @details This view provides user's gmail id , if he has one , to the it's template where we have an iframe
# which will display his current status of google calendar
# 
# Also a link is provided where he can directly upload the CSV file downloaded earlier to get the changes in Google Calendar
@login_required
def googleConnector(request):
	print(request.user.email)
	filename = "sched"+str(request.user)+".csv"
	try:
		os.remove(filename)
	except OSError:
		pass	
	text = None
	mail = request.user.email
	if mail is not None:
		mach = re.match("^[a-z0-9]+[\.'\-a-z0-9_]*[a-z0-9]+@(gmail|googlemail)\.com$", mail)
		if bool(mach):
			text = mail.split('@',1)[0]
	print (text)
	return render(request,'googleConnector.html',{'text': text})


## CompletedList is the view which lists events of user that he has marked aas completed
# @param request basic call for a view in django
# @details This view gets all events list completed by user 
@login_required
def CompletedList(request):
	user = request.user
	List = Event.objects.filter(UserProfile=user.profile, Completed = True)
	context = {'user': user , 'List': List}
	# print(List)
	template = 'basicfeedback.html'
	return render(request,template,context)
## MarkItCompleted is the intermediate view called by view EventBeforeDate to change the completed field of a view
# @param request basic call for a view in django which provides who is current user 
# @param pk EventID whose field named Completed needs to be change 
@login_required

getSchedGo/getSchedGo/statistics/templates/basicStatistics.html
{% extends 'base.html'%} <!--A way to pull content from earliertemplate base.html -->
{% load mathfilters %}
{% load staticfiles %}
{% block content %}
<select onchange="this.options[this.selectedIndex].value && (window.location = this.options[this.selectedIndex].value);">
	<option value="" selected disabled hidden>Choose the day here</option>
  <option value="{% url 'statistics:TodayStatistic' %}"><a href="{% url 'statistics:TodayStatistic' %}"> Today</a></option>
  <option value="{% url 'statistics:AnyDayStatistics' 1 %}"><a href="{% url 'statistics:AnyDayStatistics' 1 %}"> Yesterday</a></option>
  <option value="{% url 'statistics:AnyDayStatistics' 2 %}"><a href="{% url 'statistics:AnyDayStatistics' 2 %}"> Day Before Yesterday</a></option>
</select><br>
<!-- ActiveDay: {{ TodaysStats.linkedDay.Active_day|date:"M d, Y" }}<br>
 --><div class="container">
  <div class="page-header">
    <h3> {{ TodaysStats.linkedDay.Active_day|date:"M d, Y" }} </h3>
    </div></div>



<div class="table-responsive">
  <table class = "table table-hover table-condesed">
    <thead>
      <tr>
        <th>
          &nbsp;
        </th>
        <th>
          Event Type
        </th>
        <th>
          Scheduled Hours
        </th>
        <th>
          Completed Hours
        </th>
      </tr>
    </thead>
    <tbody>
      <tr class="success">
        <td>A.</td>
        <td>Self Study</td>
        <td>{{ TodaysStats.SelfStudy|div:2 }}</td>
        <td>{{ TodaysStats.CompletedSelfStudy|div:2 }}</td>
      </tr>
      <tr  class="info">
         <td>B.</td>
       <td>Class Timings</td>
        <td>{{ TodaysStats.ClassTiming|div:2 }}</td>
        <td>{{ TodaysStats.CompletedClassTiming|div:2 }}</td>
      </tr>
      <tr >
          <td>C.</td>
      <td>Extra Self Study</td>
        <td>{{ TodaysStats.ExtraStudyTime|div:2 }}</td>
        <td>{{ TodaysStats.CompletedExtraStudyTime|div:2 }}</td>
      </tr>
      <tr class="danger">
            <td>D.</td>
    <td>Extra Curriculars</td>
        <td>{{ TodaysStats.ExtraCurricularsTime|div:2 }}</td>
        <td>{{ TodaysStats.CompletedExtraCurricularsTime|div:2 }}</td>
      </tr>
      <tr class="warning">
           <td>E.</td>
     <td>Miscellaneous</td>
        <td>{{  TodaysStats.MiscellaneousTime|div:2 }}</td>
        <td>{{ TodaysStats.CompletedMiscellaneousTime|div:2 }}</td>
      </tr>
    </tbody>


  </table>
</div>

<style type="text/css">
.progress-bar-striped:hover {
     animation: progress-bar-stripes 2.5s ease-out infinite;
}
</style>

Distribution Percentage of whole day over activity<br>
<div class="progress">
{% if percentage.PercentageSelfStudy != 0 %}
<div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" style="width:{{ percentage.PercentageSelfStudy }}%">
    A
  </div>
{% endif %}
{% if percentage.PercentageClassTiming != 0 %}
   <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" style="width:{{ percentage.PercentageClassTiming }}%;">
    B
  </div>
{% endif %}
{% if percentage.PercentageExtraStudyTime != 0 %}
  <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" style="width:{{ percentage.PercentageExtraStudyTime }}%;background-color:grey;">
    C
  </div>
{% endif %}
{% if percentage.PercentageExtraCurricularsTime != 0 %}
  <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" style="width:{{ percentage.PercentageExtraCurricularsTime }}%">
    D
  </div>
{% endif %}
{% if percentage.PercentageMiscellaneousTime != 0 %}
  <div class="progress-bar progress-bar-warning progress-bar-striped" role="progressbar" style="width:{{ percentage.PercentageMiscellaneousTime }}%;">
    E
  </div>
{% endif %}
</div>

{% if percentage.TotalSchedTime != 0 %}
Relative distribution over the day <br>
<div class="progress">
{% if percentage.RelativePercentageSelfStudy != 0 %}
<div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" style="width:{{ percentage.RelativePercentageSelfStudy }}%">
    A
  </div>
{% endif %}
{% if percentage.RelativePercentageClassTiming != 0 %}
   <div class="progress-bar progress-bar-info" role="progressbar" style="width:{{ percentage.RelativePercentageClassTiming }}%;">
    B
  </div>
  {% endif %}
{% if percentage.RelativePercentageExtraStudyTime != 0 %}
  <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" style="width:{{ percentage.RelativePercentageExtraStudyTime }}%;background-color:grey;">
    C
  </div>
{% endif %}
{% if percentage.RelativePercentageExtraCurricularsTime != 0 %}
  <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" style="width:{{ percentage.RelativePercentageExtraCurricularsTime }}%">
    D
  </div>
{% endif %}
{% if percentage.RelativePercentageMiscellaneousTime != 0 %}
  <div class="progress-bar progress-bar-warning progress-bar-striped" role="progressbar" style="width:{{ percentage.RelativePercentageMiscellaneousTime }}%;">
    E
  </div>
{% endif %}
</div>
{% endif %}


















{% if not percentage.ScheduledCompletedSelfStudy is None %}
Percentage of SelfSudy completed <br>
<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar"
  aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:{{ percentage.ScheduledCompletedSelfStudy }}%">
    {{ percentage.ScheduledCompletedSelfStudy }}%
  </div>
</div>
{% endif %}
{% if not percentage.ScheduledCompletedClassTiming is None %}
Percentage of Class Timing completed <br>
<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar"
  aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:{{ percentage.ScheduledCompletedClassTiming }}%">
    {{ percentage.ScheduledCompletedClassTiming }}%
  </div>
</div>
{% endif %}
{% if not percentage.ScheduledCompletedExtraStudyTime is None %}
Percentage of Extra Study Events completed <br>
<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar"
  aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:{{ percentage.ScheduledCompletedExtraStudyTime }}%">
    {{ percentage.ScheduledCompletedExtraStudyTime }}%
  </div>
</div>
{% endif %}
{% if not percentage.ScheduledCompletedMiscellaneousTime is None %}
Percentage of Miscellaneous timing completed <br>
<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar"
  aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:{{ percentage.ScheduledCompletedMiscellaneousTime }}%">
    {{ percentage.ScheduledCompletedMiscellaneousTime }}%
  </div>
</div>
{% endif %}
{% if not percentage.ScheduledCompletedExtraCurricularsTime is None %}
Percentage of Extra-Curricular timing completed <br>
<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar"
  aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:{{ percentage.ScheduledCompletedExtraCurricularsTime}}%">
    {{ percentage.ScheduledCompletedExtraCurricularsTime }}%
  </div>
</div>
{% endif %}

{% endblock %}

getSchedGo/getSchedGo/statistics/templates/basicfeedback.html
{% extends 'base.html'%} <!--A way to pull content from earliertemplate base.html -->
{% load staticfiles %}
{% block content %}
Hi {{ user }}<br>

  {% if List %}
<p>
   {% for Event in List %}
   <div class="row event-holder" id="event{{ forloop.counter }}" style="background-color: white; color:#033a22; font-family: 'Alegreya SC';font-size: 24px;">
<div class="col-md-6">
         <h3> {{ Event.name }} </h3>
         <h4> From : {{Event.StartDate }} {{ Event.StartTime }} </h4>
         <h4> To : {{ Event.EndDate  }} {{ Event.EndTime }} </h4>
         <h4> DeadLine : {{ Event.DeadLineDate }} {{ Event.DeadLineTime }} </h4>
         {% if Event.ScheduledStartTime %}
         <h4> Scheduled from {{ Event.ScheduledStartTime }} to {{ Event.ScheduledEndTime }}</h4>
         {% endif %}
      </div>
      <div class="col-md-5" >
         {% if not Event.Completed %}
         <a href="{% url 'statistics:MarkItCompleted' Event.id %}">Yah I did it</a><br>
         {% if not Event.Type == 'A' %}
         <a href="{% url 'Timetable:EditEvent' Event.id %}">No I missed it. Edit and Reschedule it</a><br>
         <a href="{% url 'Timetable:DeleteEvent' Event.id %}">Sorry I missed. Let's delete it. I don't wanna reschedule</a><br>
         {% endif %}
         {% else %}
         <h4>Completed</h4>
      {% endif  %}
<!--          <a href="{% url 'Timetable:DeleteEvent' Event.id %}">No I couldn't Do it</a><br>
 -->      </div>
    </div>
   {% endfor %}
</p>
{% else %}
   <p>No Events are available.</p>
{% endif %}
</div>
<p style="margin-top: 5em;">&nbsp;</p>


{% endblock %}

getSchedGo/getSchedGo/statistics/templates/googleConnector.html
{% extends 'base.html'%} <!--A way to pull content from earliertemplate base.html -->
{% load staticfiles %}
{% block content %}

<p class="lead" style="font-size: 12pt; padding: 0rem 2rem ; text-align: center;"><a href="{% url 'statistics:AheadOfTime' %}">CLICK TO Generate CSV to export to calender</a></p>

<style type="text/css">
	.starter-template {
  padding: 0.3rem 1.5rem;
  text-align: center;
}
</style>   
{% if text %}
<div class="container starter-template">
	<iframe src="https://calendar.google.com/calendar/embed?title=Your%20Schedule%20is%20Served&amp;showCalendars=0&amp;showTz=0&amp;mode=WEEK&amp;height=500&amp;wkst=2&amp;bgcolor=%23c0c0c0&amp;src={{ text }}%40gmail.com&amp;color=%2329527A&amp;src=en.indian%23holiday%40group.v.calendar.google.com&amp;color=%23125A12&amp;ctz=Asia%2FCalcutta" style="border:solid 1px #777" width="800" height="500" frameborder="0" scrolling="no"></iframe>
</div>
{% endif %}


 <div class="container">
      <div class="starter-template">
        <h1><a href="https://calendar.google.com/calendar/r/settings/export" target="_blank">Add CSV from your PC to google calender</a>
</h1>
        <p class="lead">In the Google Calender window upload the file downlaoded from this website in the import calender option<br> 
        	For a detailed help. <a href="https://support.google.com/calendar/answer/37118?hl=en">here</a><br>
        If you are unable to see your calender, please login to the google account in your browser to let the system do the work.
        </p>
      </div>

    </div>


{% endblock %}